### ISSUE TITLE
 how to set up and is it possible to add many accounts for uploading?

### ISSUE THREAD

**Issue by maksblak777** [stvoidit/youtube_autouploader#2]
how to set up and is it possible to add many accounts for uploading?

**Comment by stvoidit** [comment]
Only one account.
You need to download a file with credentials from google and put it next to it (read the code, there are 2 keys in the json file - a token and a refresh token). I do not support this program, I advise you to make a fork if you want to use it.

https://developers.google.com/workspace/guides/create-credentials?hl=en

**Comment by maksblak777** [comment]
sorry but thanks

**Comment by stvoidit** [comment]
> sorry but thanks

No problems. In short, this program monitors files in the specified folder, makes a record of those already uploaded to SQLite and when it sees a new file in the folder, it uploads it to YouTube.

**Comment by maksblak777** [comment]
it’s sad that it won’t work to make it so that videos are uploaded to many channels at once. but still thanks for answering
